/* JengaFM — Comprehensive Service Catalogue data
   Organised into logical categories for the accordion-driven Services page. */

const ICONS = {
  building: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 21V5a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v16"/><path d="M15 21V9a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v12"/><path d="M9 8h2M9 12h2M9 16h2"/></svg>',
  bolt: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2 4 14h7l-1 8 9-12h-7l1-8Z"/></svg>',
  droplet: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2s7 7.5 7 12.5A7 7 0 0 1 5 14.5C5 9.5 12 2 12 2Z"/></svg>',
  flame: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22a6.5 6.5 0 0 0 6.5-6.5c0-3-2-5-3.2-7-.5 1.4-1.3 2.2-2.1 2.4C13.7 8.4 13 5.8 11 2c-1 3-3.4 5-4 8-1 4.5 1 7 1 7A6.5 6.5 0 0 0 12 22Z"/></svg>',
  shield: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 4 6v6c0 5 3.4 8.4 8 9 4.6-.6 8-4 8-9V6l-8-3Z"/><path d="m9 12 2 2 4-4"/></svg>',
  sparkles: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2 2M16 16l2 2M6 18l2-2M16 8l2-2"/></svg>',
  leaf: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 4C10 4 4 10 4 18v2h2c8 0 14-6 14-16Z"/><path d="M6 20c0-6 4-10 10-12"/></svg>',
  clipboard: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="4" width="12" height="17" rx="2"/><path d="M9 4V3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v1"/><path d="m9 13 2 2 4-4"/></svg>',
  tool: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.6 2.6-2-2 2.6-2.6Z"/></svg>',
  layers: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 17l9 5 9-5"/></svg>',
  check: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m20 6-11 11L4 12"/></svg>',
  arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  chevron: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>',
  mail: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 7 10 6 10-6"/></svg>',
  pin: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>',
  clock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg>',
};

const SERVICE_CATEGORIES = [
  {
    id: "building-maintenance",
    name: "Building Maintenance",
    icon: ICONS.building,
    description: "The day-to-day and long-term upkeep of a building's fabric and finishes — from planned inspections to emergency repairs — keeping every site safe, compliant, and presentable.",
    examples: [
      "Scheduled PPM inspections and servicing rounds",
      "Fabric repairs to roofs, walls, doors and windows",
      "24/7 emergency call-out response",
      "Internal fit and finish repairs (plaster, paint, flooring)",
    ],
    industries: ["Offices", "Retail", "Residential blocks", "Industrial sites", "Public sector"],
    benefits: [
      "One provider for every trade instead of juggling multiple contractors",
      "Reduced downtime through planned preventative maintenance",
      "24/7 emergency response protects assets and occupants",
    ],
    services: [
      "Planned Preventative Maintenance (PPM)", "Reactive Maintenance", "Emergency Call-Outs (24/7)",
      "General Building Repairs", "Handyman Services", "Building Fabric Maintenance",
      "Internal & External Repairs", "Roofing Repairs", "Guttering & Rainwater Systems",
      "Brickwork Repairs", "Masonry Repairs", "Plastering", "Rendering", "Painting & Decorating",
      "Carpentry & Joinery", "Flooring Repairs", "Ceiling Repairs", "Partition Walls",
      "Door Installation & Repairs", "Window Repairs & Replacement", "Glazing",
      "Locksmith Services", "Roller Shutters", "Automatic Doors", "Fire Doors",
    ],
  },
  {
    id: "mechanical-electrical",
    name: "Mechanical & Electrical (M&E)",
    icon: ICONS.bolt,
    description: "Installation, servicing, and compliance testing of the electrical, heating, ventilation and mechanical plant that keeps a building running safely and efficiently.",
    examples: [
      "EICR fixed wire and PAT testing programmes",
      "HVAC and boiler servicing contracts",
      "Emergency and LED lighting upgrades",
      "Distribution board and consumer unit works",
    ],
    industries: ["Healthcare", "Education", "Industrial sites", "Offices", "Hospitality"],
    benefits: [
      "Certified engineers keep statutory compliance up to date",
      "Proactive servicing reduces plant failure and energy waste",
      "Single helpdesk coordinates electrical and mechanical works together",
    ],
    services: [
      "Electrical Installation", "Electrical Repairs", "Emergency Electricians", "Consumer Units",
      "Distribution Boards", "Lighting Installation", "Emergency Lighting", "LED Upgrades",
      "PAT Testing", "Fixed Wire Testing (EICR)", "Power Distribution", "Generator Maintenance",
      "UPS Systems", "HVAC Installation", "HVAC Maintenance", "Air Conditioning", "Heating Systems",
      "Boilers", "Ventilation", "Heat Pumps", "Pumps", "Pipework", "Mechanical Plant Maintenance",
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: ICONS.droplet,
    description: "Complete plumbing and water systems care, from routine washroom maintenance to leak detection, drainage, and legionella-compliant water hygiene programmes.",
    examples: [
      "Leak detection and burst pipe repairs",
      "Drain unblocking and drainage repairs",
      "Legionella risk assessments and water hygiene monitoring",
      "Hot and cold water system maintenance",
    ],
    industries: ["Healthcare", "Hospitality", "Residential blocks", "Education", "Offices"],
    benefits: [
      "Rapid response minimises water damage and business disruption",
      "Water hygiene compliance protects occupant health",
      "Planned tank and pump maintenance extends asset life",
    ],
    services: [
      "General Plumbing", "Leak Detection", "Burst Pipes", "Drainage Repairs", "Drain Unblocking",
      "Toilet Repairs", "Washroom Maintenance", "Hot Water Systems", "Cold Water Systems",
      "Water Hygiene", "Legionella Compliance", "Pump Maintenance", "Tank Maintenance",
    ],
  },
  {
    id: "fire-life-safety",
    name: "Fire & Life Safety",
    icon: ICONS.flame,
    description: "End-to-end fire protection services that keep occupants safe and buildings compliant — covering detection, suppression, containment, and statutory inspections.",
    examples: [
      "Fire alarm and extinguisher servicing",
      "Fire door inspections and remedial repairs",
      "Sprinkler and dry riser system maintenance",
      "Fire stopping and compartmentation surveys",
    ],
    industries: ["Healthcare", "Education", "Residential blocks", "Public sector", "Industrial sites"],
    benefits: [
      "Reduces fire risk and supports insurance and legal compliance",
      "Coordinated inspection scheduling avoids missed statutory deadlines",
      "Clear reporting trail for Fire Risk Assessment remedial actions",
    ],
    services: [
      "Fire Alarm Systems", "Fire Extinguishers", "Emergency Lighting", "Fire Door Inspections",
      "Fire Door Repairs", "Fire Risk Remedial Works", "Smoke Ventilation Systems", "Dry Risers",
      "Sprinkler Systems", "Fire Stopping",
    ],
  },
  {
    id: "security-services",
    name: "Security Services",
    icon: ICONS.shield,
    description: "Protecting people, premises and assets with modern electronic security systems — installed, maintained, and monitored to a consistently high standard.",
    examples: [
      "CCTV design, installation and maintenance",
      "Access control and intercom system upgrades",
      "Intruder alarm servicing and monitoring",
      "Automated gate and barrier installation",
    ],
    industries: ["Retail", "Warehouses", "Residential blocks", "Offices", "Public sector"],
    benefits: [
      "Integrated systems give a single view of site security",
      "Rapid fault response keeps protection continuous",
      "Scalable across single sites or nationwide portfolios",
    ],
    services: [
      "CCTV Installation", "CCTV Maintenance", "Access Control", "Intercom Systems",
      "Intruder Alarms", "Barrier Systems", "Gate Automation", "Security Lighting",
    ],
  },
  {
    id: "cleaning-services",
    name: "Cleaning Services",
    icon: ICONS.sparkles,
    description: "Professional cleaning and hygiene programmes tailored to the demands of the site — from daily office cleans to high-level and specialist deep cleaning.",
    examples: [
      "Daily and periodic office and washroom cleaning",
      "High-level, window and pressure washing",
      "Carpet and deep cleaning programmes",
      "Consumable supply and hygiene servicing",
    ],
    industries: ["Offices", "Retail", "Hospitality", "Healthcare", "Education"],
    benefits: [
      "Consistent presentation supports brand and occupant wellbeing",
      "Flexible schedules fit around business operating hours",
      "Managed consumables remove day-to-day admin burden",
    ],
    services: [
      "Commercial Cleaning", "Office Cleaning", "Deep Cleaning", "Washroom Cleaning",
      "Carpet Cleaning", "Window Cleaning", "High-Level Cleaning", "Pressure Washing",
      "Graffiti Removal", "Waste Management", "Hygiene Services", "Consumable Supplies",
    ],
  },
  {
    id: "grounds-maintenance",
    name: "Grounds Maintenance",
    icon: ICONS.leaf,
    description: "Keeping external estates, car parks and landscaped areas safe, tidy and well presented all year round, including winter gritting and snow response.",
    examples: [
      "Grounds and landscape maintenance visits",
      "Car park line marking and surface upkeep",
      "Hedge, tree and grass maintenance programmes",
      "Winter gritting and snow clearance response",
    ],
    industries: ["Retail", "Industrial sites", "Residential blocks", "Public sector", "Warehouses"],
    benefits: [
      "Well-kept grounds enhance first impressions and site value",
      "Proactive gritting reduces slip and liability risk",
      "Seasonal planning keeps external estates compliant and tidy",
    ],
    services: [
      "Landscaping", "Grass Cutting", "Hedge Trimming", "Weed Control", "Tree Maintenance",
      "Car Park Maintenance", "Line Marking", "External Cleaning", "Gritting", "Snow Clearance",
    ],
  },
  {
    id: "compliance-statutory",
    name: "Compliance & Statutory Services",
    icon: ICONS.clipboard,
    description: "Independent surveys, testing and reporting that keep a building's statutory and regulatory obligations on track, with full certification and audit trails.",
    examples: [
      "Health & safety and building compliance audits",
      "Electrical, gas and fire compliance testing",
      "Asset and condition surveys",
      "Centralised compliance and certification reporting",
    ],
    industries: ["Healthcare", "Education", "Public sector", "Offices", "Residential blocks"],
    benefits: [
      "Reduces legal and insurance risk through documented compliance",
      "Single dashboard for certification renewal dates",
      "Independent surveys support informed capital planning",
    ],
    services: [
      "Health & Safety Compliance", "Building Compliance", "Electrical Compliance", "Gas Compliance",
      "Fire Compliance", "Water Hygiene", "Risk Assessments", "Asset Surveys", "Condition Surveys",
      "Compliance Reporting", "Certification Management",
    ],
  },
  {
    id: "specialist-services",
    name: "Specialist Services",
    icon: ICONS.tool,
    description: "Project-based works for clients who need more than routine maintenance — refurbishments, fit-outs, and consultancy delivered with full project management.",
    examples: [
      "Office and retail fit-out projects",
      "Dilapidation and end-of-lease works",
      "Space planning and move management",
      "Small-scale construction and building alteration projects",
    ],
    industries: ["Offices", "Retail", "Hospitality", "Public sector", "Education"],
    benefits: [
      "Single point of project management from design to handover",
      "Reduces disruption through experienced planning and sequencing",
      "Consultancy support helps optimise space and cost",
    ],
    services: [
      "Refurbishments", "Office Fit-Outs", "Dilapidation Works", "Building Alterations",
      "Small Construction Projects", "Facilities Consultancy", "Space Planning",
      "Move Management", "Project Management", "Asset Management",
    ],
  },
  {
    id: "property-support",
    name: "Property Support",
    icon: ICONS.layers,
    description: "Strategic, multi-site facilities management delivered as Hard FM, Soft FM or a fully integrated Total Facilities Management (TFM) contract, backed by a dedicated helpdesk.",
    examples: [
      "Multi-site and nationwide FM contract delivery",
      "24/7 facilities helpdesk and reactive dispatch",
      "Planned maintenance contract management",
      "Site inspections, audits and contractor management",
    ],
    industries: ["Retail chains", "Warehouses", "Public sector", "Healthcare", "Offices"],
    benefits: [
      "One contract, one invoice, one point of contact nationwide",
      "Consistent service standards across every site",
      "Helpdesk-led reporting gives full visibility of maintenance activity",
    ],
    services: [
      "Multi-Site Facilities Management", "Hard FM", "Soft FM", "Total Facilities Management (TFM)",
      "Facilities Helpdesk", "Planned Maintenance Contracts", "Reactive Maintenance Contracts",
      "Site Inspections", "Building Audits", "Contractor Management",
    ],
  },
];

const INDUSTRIES_SERVED = [
  "Offices", "Retail", "Industrial Sites", "Healthcare", "Education",
  "Hospitality", "Residential Blocks", "Warehouses", "Public Sector",
];
